"""create standart table

Revision ID: f14447903f40
Revises: 
Create Date: 2024-10-10 12:24:36.896404

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "f14447903f40"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "vk_standard_event",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=True),
        sa.Column("last_name", sa.String(length=256), nullable=True),
        sa.Column("first_name", sa.String(length=256), nullable=True),
        sa.Column("patronymic", sa.String(length=256), nullable=True),
        sa.Column("date_of_birth", sa.String(length=256), nullable=True),
        sa.Column("phone_number", sa.String(length=256), nullable=True),
        sa.Column("email_address", sa.String(length=256), nullable=True),
        sa.Column("passport_series", sa.String(length=256), nullable=True),
        sa.Column("passport_number", sa.String(length=256), nullable=True),
        sa.Column("foreign_passport", sa.String(length=256), nullable=True),
        sa.Column("snils", sa.String(length=256), nullable=True),
        sa.Column("inn", sa.String(length=256), nullable=True),
        sa.Column("gender", sa.String(length=256), nullable=True),
        sa.Column("month", sa.String(length=256), nullable=True),
        sa.Column("day", sa.String(length=256), nullable=True),
        sa.Column("year", sa.String(length=256), nullable=True),
        sa.Column("full_address", sa.String(length=256), nullable=True),
        sa.Column("street_address", sa.String(length=256), nullable=True),
        sa.Column("region", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=256), nullable=True),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("password_cleartext", sa.String(length=256), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("unknown_hash", sa.String(length=256), nullable=True),
        sa.Column("hash_salt", sa.String(length=256), nullable=True),
        sa.Column("ipv4_address", sa.String(length=256), nullable=True),
        sa.Column("ipv6_address", sa.String(length=256), nullable=True),
        sa.Column("telegram_id", sa.String(length=256), nullable=True),
        sa.Column("instagram_name", sa.String(length=256), nullable=True),
        sa.Column("registration_date", sa.String(length=256), nullable=True),
        sa.Column("access_date", sa.String(length=256), nullable=True),
        sa.Column("last_login_date", sa.String(length=256), nullable=True),
        sa.Column("related_person", sa.String(length=256), nullable=True),
        sa.Column("driver_license_number", sa.String(length=256), nullable=True),
        sa.Column("oms_policy_number", sa.String(length=256), nullable=True),
        sa.Column("military_id", sa.String(length=256), nullable=True),
        sa.Column("pension_certificate", sa.String(length=256), nullable=True),
        sa.Column("birth_certificate_number", sa.String(length=256), nullable=True),
        sa.Column("residence_permit", sa.String(length=256), nullable=True),
        sa.Column("temporary_residence_permit", sa.String(length=256), nullable=True),
        sa.Column("migration_card", sa.String(length=256), nullable=True),
        sa.Column("labor_book", sa.String(length=256), nullable=True),
        sa.Column("tax_certificate", sa.String(length=256), nullable=True),
        sa.Column("student_id", sa.String(length=256), nullable=True),
        sa.Column("work_permit", sa.String(length=256), nullable=True),
        sa.Column("marital_status", sa.String(length=256), nullable=True),
        sa.Column("place_of_birth", sa.String(length=256), nullable=True),
        sa.Column("nationality", sa.String(length=256), nullable=True),
        sa.Column("ethnicity", sa.String(length=256), nullable=True),
        sa.Column("social_security_number", sa.String(length=256), nullable=True),
        sa.Column("bank_account_number", sa.String(length=256), nullable=True),
        sa.Column("credit_card_number", sa.String(length=256), nullable=True),
        sa.Column("credit_card_cvv", sa.String(length=256), nullable=True),
        sa.Column("credit_card_date", sa.String(length=256), nullable=True),
        sa.Column("passport_expiry_date", sa.String(length=256), nullable=True),
        sa.Column("employment_status", sa.String(length=256), nullable=True),
        sa.Column("employer", sa.String(length=256), nullable=True),
        sa.Column("job_title", sa.String(length=256), nullable=True),
        sa.Column("income", sa.String(length=256), nullable=True),
        sa.Column("education_level", sa.String(length=256), nullable=True),
        sa.Column("degree", sa.String(length=256), nullable=True),
        sa.Column("social_media_profile", sa.String(length=256), nullable=True),
        sa.Column("website", sa.String(length=256), nullable=True),
        sa.Column("vkontakte_id", sa.String(length=256), nullable=True),
        sa.Column("vkontakte_url", sa.String(length=256), nullable=True),
        sa.Column("github_id", sa.String(length=256), nullable=True),
        sa.Column("linkedin_id", sa.String(length=256), nullable=True),
        sa.Column("skype_id", sa.String(length=256), nullable=True),
        sa.Column("fax_number", sa.String(length=256), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=256), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=256), nullable=True),
        sa.Column("emergency_contact_relationship", sa.String(length=256), nullable=True),
        sa.Column("insurance_policy_number", sa.String(length=256), nullable=True),
        sa.Column("insurance_provider", sa.String(length=256), nullable=True),
        sa.Column("vehicle_registration_number", sa.String(length=256), nullable=True),
        sa.Column("license_plate_number", sa.String(length=256), nullable=True),
        sa.Column("loyalty_card_number", sa.String(length=256), nullable=True),
        sa.Column("blood_type", sa.String(length=256), nullable=True),
        sa.Column("legal_cases", sa.String(length=256), nullable=True),
        sa.Column("shopping_history", sa.String(length=256), nullable=True),
        sa.Column("pet_name", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "standard_event",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=True),
        sa.Column("last_name", sa.String(length=256), nullable=True),
        sa.Column("first_name", sa.String(length=256), nullable=True),
        sa.Column("patronymic", sa.String(length=256), nullable=True),
        sa.Column("date_of_birth", sa.String(length=256), nullable=True),
        sa.Column("phone_number", sa.String(length=256), nullable=True),
        sa.Column("email_address", sa.String(length=256), nullable=True),
        sa.Column("passport_series", sa.String(length=256), nullable=True),
        sa.Column("passport_number", sa.String(length=256), nullable=True),
        sa.Column("foreign_passport", sa.String(length=256), nullable=True),
        sa.Column("snils", sa.String(length=256), nullable=True),
        sa.Column("inn", sa.String(length=256), nullable=True),
        sa.Column("gender", sa.String(length=256), nullable=True),
        sa.Column("month", sa.String(length=256), nullable=True),
        sa.Column("day", sa.String(length=256), nullable=True),
        sa.Column("year", sa.String(length=256), nullable=True),
        sa.Column("full_address", sa.String(length=256), nullable=True),
        sa.Column("street_address", sa.String(length=256), nullable=True),
        sa.Column("region", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=256), nullable=True),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("password_cleartext", sa.String(length=256), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("unknown_hash", sa.String(length=256), nullable=True),
        sa.Column("hash_salt", sa.String(length=256), nullable=True),
        sa.Column("ipv4_address", sa.String(length=256), nullable=True),
        sa.Column("ipv6_address", sa.String(length=256), nullable=True),
        sa.Column("telegram_id", sa.String(length=256), nullable=True),
        sa.Column("instagram_name", sa.String(length=256), nullable=True),
        sa.Column("registration_date", sa.String(length=256), nullable=True),
        sa.Column("access_date", sa.String(length=256), nullable=True),
        sa.Column("last_login_date", sa.String(length=256), nullable=True),
        sa.Column("related_person", sa.String(length=256), nullable=True),
        sa.Column("driver_license_number", sa.String(length=256), nullable=True),
        sa.Column("oms_policy_number", sa.String(length=256), nullable=True),
        sa.Column("military_id", sa.String(length=256), nullable=True),
        sa.Column("pension_certificate", sa.String(length=256), nullable=True),
        sa.Column("birth_certificate_number", sa.String(length=256), nullable=True),
        sa.Column("residence_permit", sa.String(length=256), nullable=True),
        sa.Column("temporary_residence_permit", sa.String(length=256), nullable=True),
        sa.Column("migration_card", sa.String(length=256), nullable=True),
        sa.Column("labor_book", sa.String(length=256), nullable=True),
        sa.Column("tax_certificate", sa.String(length=256), nullable=True),
        sa.Column("student_id", sa.String(length=256), nullable=True),
        sa.Column("work_permit", sa.String(length=256), nullable=True),
        sa.Column("marital_status", sa.String(length=256), nullable=True),
        sa.Column("place_of_birth", sa.String(length=256), nullable=True),
        sa.Column("nationality", sa.String(length=256), nullable=True),
        sa.Column("ethnicity", sa.String(length=256), nullable=True),
        sa.Column("social_security_number", sa.String(length=256), nullable=True),
        sa.Column("bank_account_number", sa.String(length=256), nullable=True),
        sa.Column("credit_card_number", sa.String(length=256), nullable=True),
        sa.Column("credit_card_cvv", sa.String(length=256), nullable=True),
        sa.Column("credit_card_date", sa.String(length=256), nullable=True),
        sa.Column("passport_expiry_date", sa.String(length=256), nullable=True),
        sa.Column("employment_status", sa.String(length=256), nullable=True),
        sa.Column("employer", sa.String(length=256), nullable=True),
        sa.Column("job_title", sa.String(length=256), nullable=True),
        sa.Column("income", sa.String(length=256), nullable=True),
        sa.Column("education_level", sa.String(length=256), nullable=True),
        sa.Column("degree", sa.String(length=256), nullable=True),
        sa.Column("social_media_profile", sa.String(length=256), nullable=True),
        sa.Column("website", sa.String(length=256), nullable=True),
        sa.Column("vkontakte_id", sa.String(length=256), nullable=True),
        sa.Column("vkontakte_url", sa.String(length=256), nullable=True),
        sa.Column("github_id", sa.String(length=256), nullable=True),
        sa.Column("linkedin_id", sa.String(length=256), nullable=True),
        sa.Column("skype_id", sa.String(length=256), nullable=True),
        sa.Column("fax_number", sa.String(length=256), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=256), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=256), nullable=True),
        sa.Column("emergency_contact_relationship", sa.String(length=256), nullable=True),
        sa.Column("insurance_policy_number", sa.String(length=256), nullable=True),
        sa.Column("insurance_provider", sa.String(length=256), nullable=True),
        sa.Column("vehicle_registration_number", sa.String(length=256), nullable=True),
        sa.Column("license_plate_number", sa.String(length=256), nullable=True),
        sa.Column("loyalty_card_number", sa.String(length=256), nullable=True),
        sa.Column("blood_type", sa.String(length=256), nullable=True),
        sa.Column("legal_cases", sa.String(length=256), nullable=True),
        sa.Column("shopping_history", sa.String(length=256), nullable=True),
        sa.Column("pet_name", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("standard_event")
